#
# ~/.bashrc
#

# If not running interactively, don't do anything
clear

# Environment variables
export EDITOR='nvim'
export VISUAL='nvim'
export PATH="$PATH:/usr/local/software/bash:/usr/local/software/bin"
export TERM='xterm-256color'

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'
alias vi='nvim'
alias dblogin="PGPASSWORD=dev_db psql -U dev -h dev_db -p 5433"
alias psearch='/usr/local/software/python/scripts/project_search.py'

# Custom terminal ID
Ccol="\e[1;36m"
Rcol="\e[1;31m"
Ncol="\e[0m"
PS1="\[$Ccol\][dpad\[$Rcol\]@\[$Ccol\]\h \[$Rcol\]\W\[$Ccol\]]\[$Ncol\]\$ "

# Pyenv
export PATH="/root/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"


function nvimPlugs() {
    if [[ "$(tmux ls 2> /dev/null | grep 'install')" =~ "install" ]]; then 
        echo "0"
    else
        echo "1" 
    fi
}

installing=$(nvimPlugs)
if [[ $installing == "0" ]]; then
    echo -e "\e[1;31mNeovim plugins are installing\e[1;33m"
    count=1
    while [[ $installing == "0" ]]
    do 
        case "$count" in 

            "1")
                echo -ne "-- \033[0K\r"
                ;;
            "2")
                echo -ne "\\ \033[0K\r"
                ;;
            "3")
                echo -ne "|| \033[0K\r"
                ;;
            "4")
                echo -ne "// \\033[0K\r"
                count=0 
                ;;
        esac
        sleep 0.25 
        ((count=count+1)) 
        installing=$(nvimPlugs)
    done
    echo -e "\e[1;36mNeovim plugins installed\e[0m"
fi

